### ISSUE TITLE
TypeError: Cannot set property 'fillStyle' of null

### ISSUE THREAD

**Issue by karlosos** [cawfree/react-dark-mode-toggle#2]
Hi. First of all, great work!

I have a problem with testing components which use this button. 

Simple test:

```
import React from 'react'
import { render } from '@testing-library/react'
import App from './App'

test('renders learn react link', () => {
  const { queryByTestId } = render(<App />)
  expect(queryByTestId('App')).toBeTruthy()
  expect(queryByTestId('App').classList.contains('active')).toBeFalsy()
})
```

has output:

![https://i.imgur.com/2MxFLSa.png](https://i.imgur.com/2MxFLSa.png)

App was created with `create-react-app`. I've prepared simple repository to reproduce this problem: https://github.com/karlosos/dark-mode-toggle-failed-tests 

Maybe there's something wrong with testing config?

**Comment by cawfree** [comment]
Hey!

Thanks for your check. It looks like `lottie-react-web` depends on the HTML canvas, which requires mocking. You can achieve this by using [`jest-canvas-mock`](https://github.com/hustcc/jest-canvas-mock) and registering it within your `package.json` `setupFiles`:

```json
"jest": {
   "setupFiles": [
      "react-app-polyfill/jsdom",
      "jest-canvas-mock"
   ]
}
```

Unfortunately, the only way I could get this to work is by using `yarn eject`, since it's not possible to override the `setupFiles` flag in a vanilla `create-react-app`. Not great. :(

On the bright side, it did flag that I've got a broken prop-type on the `speed` prop, which I'll push a fix for shortly.

Hope this helps.

**Comment by cawfree** [comment]
Okay, that fix is up in [`0.0.3`](https://github.com/cawfree/react-dark-mode-toggle/commit/10463f31e66813969b92b57b13e2a670afb19ca1).

**Comment by karlosos** [comment]
It's working. Thank you.

**Comment by cawfree** [comment]
Ah that's great to hear. Thanks for your help!
